
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Jun 16 01:39:03 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int INTERROG = 38;
  public static final int MAS_MAS = 35;
  public static final int VALOR_DOUBLE = 10;
  public static final int POR = 31;
  public static final int CHAR = 11;
  public static final int VALOR_CHAR = 12;
  public static final int PAR_AP = 40;
  public static final int IDENTIF = 2;
  public static final int MENOS_MENOS = 36;
  public static final int DOUBLE = 9;
  public static final int DOS_PUNTOS = 39;
  public static final int INT = 7;
  public static final int FOR = 20;
  public static final int AND = 22;
  public static final int IGUAL = 37;
  public static final int CORCH_CI = 43;
  public static final int OR = 21;
  public static final int CLASS = 16;
  public static final int LLAVE_AP = 44;
  public static final int DIV = 32;
  public static final int VALOR_INT = 8;
  public static final int IF = 18;
  public static final int THIS = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 17;
  public static final int TRUE = 5;
  public static final int PAR_CI = 41;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int MENOS = 30;
  public static final int NULL = 15;
  public static final int MENOR = 25;
  public static final int MOD = 33;
  public static final int VOID = 13;
  public static final int DIST_COMP = 24;
  public static final int MAYOR = 27;
  public static final int ELSE = 19;
  public static final int PUNTO = 48;
  public static final int MAYOR_IGUAL = 28;
  public static final int LLAVE_CI = 45;
  public static final int IGUAL_COMP = 23;
  public static final int MENOR_IGUAL = 26;
  public static final int FALSE = 6;
  public static final int CORCH_AP = 42;
  public static final int NEGADO = 34;
  public static final int PYC = 47;
  public static final int MAS = 29;
}

