package ast;

public enum Codigo {
    //PROGRAMA
    PROG,

    //DECLARACIONES
    DECLAR, MET,
    //Params
    PARAMETROS, PARAM,

    //TIPOS
    TIPO_INT, TIPO_DOUBLE, TIPO_CHAR, TIPO_BOOLEAN, TIPO_VOID, TIPO_NULL,
    TIPO_ARRAY, TIPO_CLASE, CLASS,

    //INSTRUCCIONES
    IF, FOR, INS_EXPR, ASIG, RETURN, RETURN_VOID, NEW_CLASE, NEW_ARRAY,
    ARGUMENTOS, ARRAY_INIT, BLOQUE_INS,VAL_MET,

    //DESIGNADORES
    //Variables
    VAL, THIS,
    //Extras
    EXTRA_VAL_PUNTO_ATRIB, EXTRA_VAL_PUNTO_MET, EXTRA_VAL_POS,

    //EXPRESIONES
    SUMA, RESTA, MUL, DIV, MOD, AND, OR, IGUAL_COMP, DIST_COMP,
    MAYOR, MAYOR_IGUAL, MENOR, MENOR_IGUAL, NEG, MAS_MAS_DER,MENOS_MENOS_DER,
    MAS_MAS_IZQ, MENOS_MENOS_IZQ, MAS_IZQ, MENOS_IZQ, OP_TER,
    //Literales
    LIT_INT,LIT_DOUBLE,LIT_CHAR,LIT_BOOLEAN,NULL
}
